packages:
  - "apps/*"
  - "packages/*"
peerDependencyRules:
  allowedVersions:
    "@emoji-mart/react@1>react": "^19.0.0"
    "@typescript-eslint/parser@8>typescript": "^7.0.0"
    "@typescript-eslint/typescript-estree@8>typescript": "^7.0.0"
    "@typescript-eslint/tsconfig-utils@8>typescript": "^7.0.0"
    "@typescript-eslint/project-service@8>typescript": "^7.0.0"
allowBuilds:
  better-sqlite3: false
  cpu-features: false
  esbuild: true
  protobufjs: true
  sharp: false
  ssh2: false
