packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  better-sqlite3: false
  cpu-features: false
  esbuild: true
  protobufjs: true
  sharp: false
  ssh2: false
minimumReleaseAgeExclude:
  - '@scalar/client-side-rendering@0.3.9'
  - '@scalar/helpers@0.11.1'
  - '@scalar/hono-api-reference@0.11.16'
  - '@scalar/schemas@0.8.3'
  - '@scalar/types@0.18.2'
  - '@scalar/validation@0.6.3'
